jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 980527kmseok@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true